const ibanRegistry = [
  {
    country: "Andorra",
    code: "AD",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!n4!n12!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Associacio de Bancs Andorrans (ABA)",
    contactEmail: "aba@aba.ad"
  },
  {
    country: "United Arab Emirates (The)",
    code: "AE",
    sepa: false,
    length: 23,
    bbanLength: "19",
    bbanStructure: "3!n16!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Oct-11",
    authority: "Central Bank of the United Arab Emirates",
    contactEmail: "rashed.alfandi@cbuae.gov.ae"
  },
  {
    country: "Albania",
    code: "AL",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "8!n16!c",
    bankIdPos: "1-8",
    bankIdPattern: "8!n",
    effectiveDate: "Apr-09",
    authority: "Bank of Albania",
    contactEmail: "vmiho@bankofalbania.org"
  },
  {
    country: "Austria",
    code: "AT",
    sepa: true,
    length: 20,
    bbanLength: "16",
    bbanStructure: "5!n11!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-07",
    authority: "Stuzza",
    contactEmail: "hendrik.muus@stuzza.at"
  },
  {
    country: "Azerbaijan",
    code: "AZ",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!a20!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jan-13",
    authority: "Central Bank of the Republic of Azerbaijan",
    contactEmail: "vahid_gurbanli@cbar.az"
  },
  {
    country: "Bosnia and Herzegovina",
    code: "BA",
    sepa: false,
    length: 20,
    bbanLength: "16",
    bbanStructure: "3!n3!n8!n2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Apr-07",
    authority: "Centralna banka Bosne I Hercegovine",
    contactEmail: "srdjan.kresic@cbbh.ba"
  },
  {
    country: "Belgium",
    code: "BE",
    sepa: true,
    length: 16,
    bbanLength: "12",
    bbanStructure: "3!n7!n2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Apr-07",
    authority: "Febelfin",
    contactEmail: "info@febelfin.be"
  },
  {
    country: "Bulgaria",
    code: "BG",
    sepa: true,
    length: 22,
    bbanLength: "18",
    bbanStructure: "4!a4!n2!n8!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Apr-07",
    authority: "Bulgarian National Bank",
    contactEmail: "rtgs@bnbank.org"
  },
  {
    country: "Bahrain",
    code: "BH",
    sepa: false,
    length: 22,
    bbanLength: "18",
    bbanStructure: "4!a14!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jan-12",
    authority: "Central Bank of Bahrain",
    contactEmail: "malfadhel@cbb.gov.bh"
  },
  {
    country: "Burundi",
    code: "BI",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "5!n5!n11!n2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Oct-21",
    authority: "Banque de la Republique du Burundi",
    contactEmail: "bernard@brb.bi"
  },
  {
    country: "Brazil",
    code: "BR",
    sepa: false,
    length: 29,
    bbanLength: "25",
    bbanStructure: "8!n5!n10!n1!a1!c",
    bankIdPos: "1-8",
    bankIdPattern: "8!n",
    effectiveDate: "Jul-13",
    authority: "Banco Central do Brasil",
    contactEmail: "nibia.quintero@bccr.fi.cr"
  },
  {
    country: "Republic of Belarus",
    code: "BY",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!c4!n16!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!c",
    effectiveDate: "Jul-17",
    authority: "National Bank of the Republic of Belarus",
    contactEmail: "N.Pelih@nbrb.by"
  },
  {
    country: "Switzerland",
    code: "CH",
    sepa: true,
    length: 21,
    bbanLength: "17",
    bbanStructure: "5!n12!c",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-07",
    authority: "SIX Interbank Clearing Ltd",
    contactEmail: "iban@six-group.com"
  },
  {
    country: "Costa Rica",
    code: "CR",
    sepa: false,
    length: 22,
    bbanLength: "18!n",
    bbanStructure: "4!n14!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Jun-11",
    authority: "Banco Central de Costa Rica",
    contactEmail: "carvajalcf@bccr.fi.cr"
  },
  {
    country: "Cyprus",
    code: "CY",
    sepa: true,
    length: 28,
    bbanLength: "24",
    bbanStructure: "3!n5!n16!c",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Apr-07",
    authority: "Central Bank of Cyprus",
    contactEmail: "PaymentSystems@centralbank.gov.cy"
  },
  {
    country: "Czechia",
    code: "CZ",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!n6!n10!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Czech National Bank",
    contactEmail: "iban.info@cnb.cz"
  },
  {
    country: "Germany",
    code: "DE",
    sepa: true,
    length: 22,
    bbanLength: "18",
    bbanStructure: "8!n10!n",
    bankIdPos: "1-8",
    bankIdPattern: "8!n",
    effectiveDate: "Jul-07",
    authority: "Bundesverband deutscher Banken",
    contactEmail: "iban@bdb.de"
  },
  {
    country: "Djibouti",
    code: "DJ",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "5!n5!n11!n2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-22",
    authority: "Banque Centrale de Djibouti",
    contactEmail: "bndj@intnet.dj"
  },
  {
    country: "Denmark",
    code: "DK",
    sepa: true,
    length: 18,
    bbanLength: "14",
    bbanStructure: "4!n9!n1!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Finance Denmark",
    contactEmail: "IBAN@FIDA.dk"
  },
  {
    country: "Dominican Republic",
    code: "DO",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!c20!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!c",
    effectiveDate: "Dec-10",
    authority: "Banco Central del República Dominicana",
    contactEmail: "sistema.pagos@bancentral.gov.do"
  },
  {
    country: "Estonia",
    code: "EE",
    sepa: true,
    length: 20,
    bbanLength: "16",
    bbanStructure: "2!n14!n",
    bankIdPos: "1-2",
    bankIdPattern: "2!n",
    effectiveDate: "Apr-07",
    authority: "Estonian Banking Association",
    contactEmail: "pangaliit@pangaliit.ee"
  },
  {
    country: "Egypt",
    code: "EG",
    sepa: false,
    length: 29,
    bbanLength: "25",
    bbanStructure: "4!n4!n17!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Jan-21",
    authority: "Central Bank of Egypt",
    contactEmail: "Shereef.Adel@Cbe.org.eg"
  },
  {
    country: "Spain",
    code: "ES",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!n4!n1!n1!n10!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Asociación Española de Banca Privada (AEB)",
    contactEmail: "pclaveria@aebanca.es"
  },
  {
    country: "Finland",
    code: "FI",
    sepa: true,
    length: 18,
    bbanLength: "14",
    bbanStructure: "3!n11!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Dec-11",
    authority: "Federation of Finnish Financial Services",
    contactEmail: "IBAN@FIDA.dk"
  },
  {
    country: "Falkland Islands",
    code: "FK",
    sepa: false,
    length: 18,
    bbanLength: "14",
    bbanStructure: "2!a12!n",
    bankIdPos: "1-2",
    bankIdPattern: "2!a",
    effectiveDate: "Jul-23",
    authority: "Falkland Islands Government",
    contactEmail: "treasury@sec.gov.fk"
  },
  {
    country: "Faroe Islands",
    code: "FO",
    sepa: false,
    length: 18,
    bbanLength: "14",
    bbanStructure: "4!n9!n1!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Finance Denmark",
    contactEmail: "IBAN@FIDA.dk"
  },
  {
    country: "France",
    code: "FR",
    sepa: true,
    length: 27,
    bbanLength: "23",
    bbanStructure: "5!n5!n11!c2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-07",
    authority: "CFONB",
    contactEmail: "cfonb@cfonb.fr"
  },
  {
    country: "United Kingdom",
    code: "GB",
    sepa: true,
    length: 22,
    bbanLength: "18",
    bbanStructure: "4!a6!n8!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "May-10",
    authority: "Payments UK Management Ltd",
    contactEmail: "James.Whittle@paymentsuk.org.uk"
  },
  {
    country: "Georgia",
    code: "GE",
    sepa: false,
    length: 22,
    bbanLength: "18",
    bbanStructure: "2!a16!n",
    bankIdPos: "1-2",
    bankIdPattern: "2!a",
    effectiveDate: "Apr-07",
    authority: "National Bank of Georgia",
    contactEmail: "Natalia.Tchkoidze@nbg.gov.ge"
  },
  {
    country: "Gibraltar",
    code: "GI",
    sepa: false,
    length: 23,
    bbanLength: "19",
    bbanStructure: "4!a15!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Apr-07",
    authority: "Financial Services Commission",
    contactEmail: "info@fsc.gi"
  },
  {
    country: "Greenland",
    code: "GL",
    sepa: false,
    length: 18,
    bbanLength: "14",
    bbanStructure: "4!n9!n1!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Finance Denmark",
    contactEmail: "IBAN@FIDA.dk"
  },
  {
    country: "Greece",
    code: "GR",
    sepa: true,
    length: 27,
    bbanLength: "23",
    bbanStructure: "3!n4!n16!c",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Sep-10",
    authority: "Hellenic Bank Association",
    contactEmail: "hba@hba.gr"
  },
  {
    country: "Guatemala",
    code: "GT",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!c20!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!c",
    effectiveDate: "Oct-24",
    authority: "Banco de Guatemala",
    contactEmail: "contabilidad@banguat.gob.gt"
  },
  {
    country: "Honduras",
    code: "HN",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!a20!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Sep-14",
    authority: "Banco Central de Honduras",
    contactEmail: "carlos.avila@bch.hn"
  },
  {
    country: "Croatia",
    code: "HR",
    sepa: true,
    length: 21,
    bbanLength: "17",
    bbanStructure: "7!n10!n",
    bankIdPos: "1-7",
    bankIdPattern: "7!n",
    effectiveDate: "Apr-07",
    authority: "Croatian National Bank",
    contactEmail: "zpp@hnb.hr"
  },
  {
    country: "Hungary",
    code: "HU",
    sepa: true,
    length: 28,
    bbanLength: "23",
    bbanStructure: "3!n4!n1!n15!n1!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Jan-11",
    authority: "Hungarian Banking Association",
    contactEmail: "hba@hba.org.hu"
  },
  {
    country: "Ireland",
    code: "IE",
    sepa: true,
    length: 22,
    bbanLength: "18",
    bbanStructure: "4!a6!n8!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jul-07",
    authority: "Banking & Payments Federation Ireland",
    contactEmail: "info@bpfi.ie"
  },
  {
    country: "Israel",
    code: "IL",
    sepa: true,
    length: 26,
    bbanLength: "22",
    bbanStructure: "3!n3!n13!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Nov-16",
    authority: "Bank of Israel",
    contactEmail: "zahav@boi.org.il"
  },
  {
    country: "Iraq",
    code: "IQ",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "4!a3!n12!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Yes",
    authority: "Central Bank of Iraq",
    contactEmail: "rami.sayeh@cbj.gov.jo"
  },
  {
    country: "Iceland",
    code: "IS",
    sepa: true,
    length: 27,
    bbanLength: "23",
    bbanStructure: "4!n2!n6!n10!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Icelandic Banks Data Centre",
    contactEmail: "hjalp@rb.is"
  },
  {
    country: "Italy",
    code: "IT",
    sepa: true,
    length: 27,
    bbanLength: "23",
    bbanStructure: "1!a5!n5!n12!c",
    bankIdPos: "1-2",
    bankIdPattern: "1!a",
    effectiveDate: "Apr-07",
    authority: "Associazione Bancaria Italiana",
    contactEmail: "r.camporeale@abi.it"
  },
  {
    country: "Jordan",
    code: "JO",
    sepa: false,
    length: 30,
    bbanLength: "27",
    bbanStructure: "4!a4!n18!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Feb-14",
    authority: "Central Bank of Jordan",
    contactEmail: "rami.sayeh@cbj.gov.jo"
  },
  {
    country: "Kuwait",
    code: "KW",
    sepa: false,
    length: 30,
    bbanLength: "27",
    bbanStructure: "4!a22!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jan-11",
    authority: "Central Bank of Kuwait",
    contactEmail: "aalghaith@cbk.gov.kw"
  },
  {
    country: "Kazakhstan",
    code: "KZ",
    sepa: false,
    length: 20,
    bbanLength: "16",
    bbanStructure: "3!n13!c",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Apr-07",
    authority: "National Bank of the Republic of Kazakhstan",
    contactEmail: "imangazina@nationalbank.kz"
  },
  {
    country: "Lebanon",
    code: "LB",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "4!n20!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Jan-10",
    authority: "BANQUE DU LIBAN",
    contactEmail: "belzouheiry@bdl.gov.lb"
  },
  {
    country: "Saint Lucia",
    code: "LC",
    sepa: false,
    length: 32,
    bbanLength: "28",
    bbanStructure: "4!a24!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jan-10",
    authority: "Saint Lucia Bureau of Standards",
    contactEmail: "t.haynes@slbs.org; info@slbs.org"
  },
  {
    country: "Liechtenstein",
    code: "LI",
    sepa: true,
    length: 21,
    bbanLength: "17",
    bbanStructure: "5!n12!c",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-07",
    authority: "Liechtenstein Bankers Association",
    contactEmail: "gert.zimmermann@bankenverband.li"
  },
  {
    country: "Lithuania",
    code: "LT",
    sepa: true,
    length: 25,
    bbanLength: "21",
    bbanStructure: "5!n11!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Jan-16",
    authority: "Bank of Lithuania",
    contactEmail: "tarpbank@lb.lt"
  },
  {
    country: "Luxembourg",
    code: "LU",
    sepa: true,
    length: 20,
    bbanLength: "16",
    bbanStructure: "3!n13!c",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Apr-07",
    authority: "ABBL - Association des Banques et Banquiers Luxembourg",
    contactEmail: "borsa@abbl.lu"
  },
  {
    country: "Latvia",
    code: "LV",
    sepa: true,
    length: 20,
    bbanLength: "16",
    bbanStructure: "4!a13!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Apr-07",
    authority: "Bank of Latvia",
    contactEmail: "Anda.Zalmane@bank.lv"
  },
  {
    country: "Libya",
    code: "LY",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "3!n3!n15!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Mar-24",
    authority: "Central Bank of Libya",
    contactEmail: "fabokhzam@cbl.gov.ly"
  },
  {
    country: "Monaco",
    code: "MC",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "5!n5!n11!c2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Dec-12",
    authority: "Principauté de Monaco",
    contactEmail: "amaf@amaf.mc"
  },
  {
    country: "Moldova",
    code: "MD",
    sepa: false,
    length: 28,
    bbanLength: "24",
    bbanStructure: "2!c18!c",
    bankIdPos: "1-2",
    bankIdPattern: "2!c",
    effectiveDate: "Oct-24",
    authority: "National Bank of Moldova",
    contactEmail: "Victor.Susu@bnm.md"
  },
  {
    country: "Montenegro",
    code: "ME",
    sepa: false,
    length: 21,
    bbanLength: "17",
    bbanStructure: "3!n13!n2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Jul-21",
    authority: "Association of Montenegrin Banks",
    contactEmail: "Mirko.Radonjic"
  },
  {
    country: "Macedonia",
    code: "MK",
    sepa: false,
    length: 30,
    bbanLength: "25",
    bbanStructure: "3!n10!c2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Jul-16",
    authority: "National Bank of the Republic of Macedonia",
    contactEmail: "aco@ic.mchamber.org.mk"
  },
  {
    country: "Mongolia",
    code: "MN",
    sepa: false,
    length: 21,
    bbanLength: "17",
    bbanStructure: "4!n12!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Oct-16",
    authority: "Bank of Mongolia (The Central Bank)",
    contactEmail: "ygoogool@bom.intnet.mu"
  },
  {
    country: "Mauritania",
    code: "MR",
    sepa: false,
    length: 25,
    bbanLength: "20",
    bbanStructure: "5!n5!n11!n2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Mar-20",
    authority: "Banque Centrale de Mauritanie",
    contactEmail: "info@maltabankers.org"
  },
  {
    country: "Malta",
    code: "MT",
    sepa: true,
    length: 30,
    bbanLength: "26",
    bbanStructure: "4!a5!n18!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Sep-14",
    authority: "Malta Bankers’ Association",
    contactEmail: "Oknan Alfredo"
  },
  {
    country: "Mauritius",
    code: "MU",
    sepa: false,
    length: 30,
    bbanLength: "26",
    bbanStructure: "4!a2!n2!n12!n3!n3!a",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Dec-16",
    authority: "The Central Bank of Mauritius",
    contactEmail: "dsp@bcstp.st"
  },
  {
    country: "Nicaragua",
    code: "NI",
    sepa: false,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!a20!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Mar-19",
    authority: "Banco Central de Nicaragua",
    contactEmail: "maria.delgado@bcr.gov.sv"
  },
  {
    country: "Netherlands (The)",
    code: "NL",
    sepa: true,
    length: 18,
    bbanLength: "14",
    bbanStructure: "4!a10!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Apr-07",
    authority: "Betaalvereniging Nederland",
    contactEmail: "sepa@betaalvereniging.nl"
  },
  {
    country: "Norway",
    code: "NO",
    sepa: false,
    length: 15,
    bbanLength: "11",
    bbanStructure: "4!n6!n1!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Aug-07",
    authority: "DnB NOR Bank",
    contactEmail: "Atle.Fjereide@dnbnor.no"
  },
  {
    country: "Oman",
    code: "OM",
    sepa: false,
    length: 23,
    bbanLength: "19",
    bbanStructure: "3!n16!c",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Jul-16",
    authority: "Central Bank of Oman",
    contactEmail: "Mohamed.alsiyabi@cbo.gov.om"
  },
  {
    country: "Pakistan",
    code: "PK",
    sepa: false,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!a16!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jan-23",
    authority: "State Bank of Pakistan",
    contactEmail: "zamir.afzal@sbp.org.pk"
  },
  {
    country: "Poland",
    code: "PL",
    sepa: true,
    length: 28,
    bbanLength: "24",
    bbanStructure: "8!n16!n",
    bankIdPos: "1-8",
    bankIdPattern: "8!n",
    effectiveDate: "Dec-16",
    authority: "Narodowy Bank Polski",
    contactEmail: "pawel.lysakowski@nbp.pl"
  },
  {
    country: "Palestine, State of",
    code: "PS",
    sepa: false,
    length: 29,
    bbanLength: "25",
    bbanStructure: "4!a21!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Mar-20",
    authority: "Palestine Monetary Authority",
    contactEmail: "rawwad@pma.ps"
  },
  {
    country: "Portugal",
    code: "PT",
    sepa: true,
    length: 25,
    bbanLength: "21",
    bbanStructure: "4!n4!n11!n2!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Dec-11",
    authority: "SIBS Forward Payment Solutions",
    contactEmail: "platni.sistem@nbs.rs"
  },
  {
    country: "Qatar",
    code: "QA",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "4!a21!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Feb-16",
    authority: "Qatar Central Bank",
    contactEmail: "ahena@qcb.gov.qa"
  },
  {
    country: "Romania",
    code: "RO",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!a16!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Apr-07",
    authority: "National Bank of Romania",
    contactEmail: "ruxandra.avram@bnro.ro"
  },
  {
    country: "Serbia",
    code: "RS",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "3!n13!n2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Jul-24",
    authority: "National bank of Serbia",
    contactEmail: "platni.sistem@nbs.rs"
  },
  {
    country: "Russia",
    code: "RU",
    sepa: false,
    length: 31,
    bbanLength: "27",
    bbanStructure: "9!n5!n15!c",
    bankIdPos: "1-9",
    bankIdPattern: "9!n",
    effectiveDate: "Jan-23",
    authority: "The Central Bank of the Russian Federation",
    contactEmail: "mmv4@cbr.ru"
  },
  {
    country: "Saudi Arabia",
    code: "SA",
    sepa: false,
    length: 22,
    bbanLength: "18",
    bbanStructure: "2!n18!c",
    bankIdPos: "1-2",
    bankIdPattern: "2!n",
    effectiveDate: "Aug-07",
    authority: "SAMA, Head Office",
    contactEmail: "gdps@sama.gov.sa"
  },
  {
    country: "Seychelles",
    code: "SC",
    sepa: false,
    length: 31,
    bbanLength: "27",
    bbanStructure: "4!a2!n2!n16!n3!a",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Oct-16",
    authority: "Central Bank of Seychelles",
    contactEmail: "Psd@cbs.sc"
  },
  {
    country: "Sudan",
    code: "SD",
    sepa: false,
    length: 18,
    bbanLength: "14",
    bbanStructure: "2!n12!n",
    bankIdPos: "1-2",
    bankIdPattern: "2!n",
    effectiveDate: "Jul-21",
    authority: "Central Bank of Sudan (CBOS)",
    contactEmail: "ahmed.elhassan@cbos.gov.sd"
  },
  {
    country: "Sweden",
    code: "SE",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "3!n16!n1!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Sep-14",
    authority: "Swedish Bankers’ Association",
    contactEmail: "lars.rutberg@bankforeningen.se"
  },
  {
    country: "Slovenia",
    code: "SI",
    sepa: true,
    length: 19,
    bbanLength: "15",
    bbanStructure: "5!n8!n2!n",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-07",
    authority: "Bank of Slovenia",
    contactEmail: "Pomoc.PS@bsi.si"
  },
  {
    country: "Slovakia",
    code: "SK",
    sepa: true,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!n6!n10!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "National Bank of Slovakia",
    contactEmail: "info@nbs.sk"
  },
  {
    country: "San Marino",
    code: "SM",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "1!a5!n5!n12!c",
    bankIdPos: "1-2",
    bankIdPattern: "1!a",
    effectiveDate: "Jul-07",
    authority: "Banca Centrale della Repubblica di San Marino",
    contactEmail: "sistemi.pagamento@bcsm.sm"
  },
  {
    country: "Somalia",
    code: "SO",
    sepa: false,
    length: 22,
    bbanLength: "18",
    bbanStructure: "4!n3!n12!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Apr-07",
    authority: "Central Bank of Somalia",
    contactEmail: "info@centralbank.gov.so"
  },
  {
    country: "Sao Tome and Principe",
    code: "ST",
    sepa: false,
    length: 25,
    bbanLength: "21",
    bbanStructure: "8!n11!n2!n",
    bankIdPos: "1-8",
    bankIdPattern: "8!n",
    effectiveDate: "Jan-16",
    authority: "Banco Central de Sao Tome e Principe",
    contactEmail: "obello@bcn.gob.ni"
  },
  {
    country: "El Salvador",
    code: "SV",
    sepa: false,
    length: 27,
    bbanLength: "23",
    bbanStructure: "4!a20!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jul-16",
    authority: "Banco Central de Reserva de El Salvador",
    contactEmail: "maria.delgado@bcr.gov.sv"
  },
  {
    country: "Timor-Leste",
    code: "TL",
    sepa: false,
    length: 23,
    bbanLength: "19",
    bbanStructure: "3!n14!n2!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Oct-16",
    authority: "Banco Central de Timor-Leste",
    contactEmail: "sara.brites@bancocentral.tl"
  },
  {
    country: "Tunisia",
    code: "TN",
    sepa: false,
    length: 26,
    bbanLength: "22",
    bbanStructure: "2!n3!n13!n2!n",
    bankIdPos: "1-2",
    bankIdPattern: "2!n",
    effectiveDate: "Sep-14",
    authority: "Tunisia’s Professional Association for Banks & Financial Institutions",
    contactEmail: "platni.sistem@nbs.rs"
  },
  {
    country: "Turkey",
    code: "TR",
    sepa: false,
    length: 25,
    bbanLength: "21",
    bbanStructure: "5!n1!n16!c",
    bankIdPos: "1-5",
    bankIdPattern: "5!n",
    effectiveDate: "Apr-12",
    authority: "Central Bank of the Republic of Turkey",
    contactEmail: "payroll@tcmb.gov.tr"
  },
  {
    country: "Ukraine",
    code: "UA",
    sepa: false,
    length: 29,
    bbanLength: "25",
    bbanStructure: "6!n19!c",
    bankIdPos: "1-6",
    bankIdPattern: "6!n",
    effectiveDate: "Mar-20",
    authority: "Association UkrSWIFT",
    contactEmail: "ukrswift@ukrswift.org"
  },
  {
    country: "Vatican City State",
    code: "VA",
    sepa: false,
    length: 22,
    bbanLength: "18",
    bbanStructure: "3!n15!n",
    bankIdPos: "1-3",
    bankIdPattern: "3!n",
    effectiveDate: "Dec-18",
    authority: "Financial Information Authority (Autorita di Informazione Finanziaria - AIF)",
    contactEmail: "aif@aif.va"
  },
  {
    country: "Virgin Islands",
    code: "VG",
    sepa: false,
    length: 24,
    bbanLength: "20",
    bbanStructure: "4!a16!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jun-14",
    authority: "VP Bank House",
    contactEmail: "diruzza@aif.va"
  },
  {
    country: "Kosovo",
    code: "XK",
    sepa: false,
    length: 20,
    bbanLength: "16",
    bbanStructure: "4!n10!n2!n",
    bankIdPos: "1-4",
    bankIdPattern: "4!n",
    effectiveDate: "Jul-24",
    authority: "Central Bank of the Republic of Kosovo",
    contactEmail: "payment.systems@bqk-kos.org"
  },
  {
    country: "Yemen",
    code: "YE",
    sepa: false,
    length: 30,
    bbanLength: "26",
    bbanStructure: "4!a4!n18!c",
    bankIdPos: "1-4",
    bankIdPattern: "4!a",
    effectiveDate: "Jul-24",
    authority: "Central Bank of Yemen",
    contactEmail: "Crater Aledaroos Street 452"
  }
];